@Backend_HostAddress = http://localhost:5043/api
@bearerToken = Bearer YOUR_JWT_TOKEN

GET {{Backend_HostAddress}}/campaign/
Accept: application/json
Authorization: {{bearerToken}}

###
GET {{Backend_HostAddress}}/campaign/2
Accept: application/json
Authorization: {{bearerToken}}

###

GET {{Backend_HostAddress}}/campaign/gm/1
Accept: application/json
Authorization: {{bearerToken}}

###
