@Backend_HostAddress = http://localhost:5043/api
@bearerToken = Bearer YOUR_JWT_TOKEN
  
GET {{Backend_HostAddress}}/character/
Accept: application/json
Authorization: {{bearerToken}}

###
GET {{Backend_HostAddress}}/character/15
Accept: application/json
Authorization: {{bearerToken}}
Authorization: {{bearerToken}}
###
GET {{Backend_HostAddress}}/character/campaign/1
Accept: application/json

###
POST {{Backend_HostAddress}}/character/
Content-Type: application/json
Authorization: {{bearerToken}}

{
  "name": "New Character",
  "campaignId": 1,
  "description": "A new character for the campaign",
  "descriptionShort": "New char"
  
}

###
PUT {{Backend_HostAddress}}/character/15
Content-Type: application/json
Authorization: {{bearerToken}}

{
  "id": 15,
  "playerId": 1,
  "name": "Updated Character",
  "campaignId": 1,
  "description": "An updated character description",
  "descriptionShort": "Updated char"
}

###
DELETE {{Backend_HostAddress}}/character/15
Authorization: {{bearerToken}}