@Backend_HostAddress = http://localhost:5043/api
@bearerToken = Bearer YOUR_JWT_TOKEN

GET {{Backend_HostAddress}}/user/
Accept: application/json
Authorization: {{bearerToken}}

###
GET {{Backend_HostAddress}}/user/1
Accept: application/json
Authorization: {{bearerToken}}